name: pyvista_cpu_lumi
channels:
  - conda-forge
  - defaults
dependencies:
  - xorg-libx11     # Fornisce libX11.so.6
  - xorg-libxext    # Fornisce libXext.so.6 (spesso necessaria anche)
  - xorg-libxau     # Dipendenza di libX11
  - xorg-libxdmcp   # Dipendenza di libX11
  - bzip2=1.0.8
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - certifi==2025.1.31
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.57.0
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - natsort==8.4.0
      - netcdf4==1.7.2
      - numpy==2.2.4
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.2.1
      - platformdirs==4.3.7
      - pooch==1.8.2
      - psutil==7.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyvista==0.44.2
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - scooby==0.10.0
      - six==1.17.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - vtk==9.3.1
      - xarray==2025.3.1
